name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Puxa o código
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Dependências de sistema
      - name: Install System Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y python3-pip git zip unzip openjdk-17-jdk-headless

      # 4) Buildozer & Cython
      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip setuptools cython buildozer

      # 5) Compila o APK
      - name: Build APK
        run: |
          yes | buildozer --storage-dir=buildozer-out android debug

      # 6) Debug: lista o conteúdo gerado
      - name: List Workspace Files
        run: |
          echo "=== Conteúdo da workspace ==="
          find . -maxdepth 5 | sed 's/^/ /'

      # 7) Publica o APK como artefato
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: whatsbotoperador-apk
          path: '**/*.apk'
