name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install System Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y python3-pip git zip unzip openjdk-17-jdk-headless

      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip setuptools cython buildozer

      - name: Build APK
        run: |
          yes | buildozer --storage-dir=buildozer-out android debug

      - name: List Workspace Files
        run: |
          echo "=== Workspace ==="
          find . -maxdepth 5 | sed 's/^/ /'
